# Generated by Django 4.1.5 on 2023-01-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_doctor_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='admin',
            new_name='user',
        ),
    ]
