# Generated by Django 4.1.5 on 2023-01-10 21:08

import api.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_doctor_nurse_alter_doctor_user_alter_nurse_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_to)),
                ('name', models.CharField(max_length=220)),
                ('room_number', models.IntegerField()),
                ('sick_name', models.CharField(max_length=300)),
                ('mobile', models.CharField(max_length=150)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='added_admin', to='api.admin')),
                ('doctor', models.ManyToManyField(related_name='doctor', to='api.doctor')),
                ('nurse', models.ManyToManyField(related_name='nurse', to='api.nurse')),
            ],
            options={
                'verbose_name': 'Patients',
                'verbose_name_plural': 'Patients',
                'db_table': 'Patients',
                'ordering': ('room_number',),
            },
        ),
    ]
