# Generated by Django 4.1.5 on 2023-01-11 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_add', to='api.doctor')),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors_add', to='api.nurse')),
            ],
        ),
    ]
