# Generated by Django 4.1.5 on 2023-01-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_addop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addop',
            name='nurse',
        ),
        migrations.AddField(
            model_name='addop',
            name='nurse',
            field=models.ManyToManyField(related_name='doctors_add', to='api.nurse'),
        ),
    ]
