# Generated by Django 4.1.5 on 2023-01-11 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_addop_nurse_addop_nurse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddOp',
        ),
    ]
