# Generated by Django 4.1.5 on 2023-01-14 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_delete_addop'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='sick_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='disease_type',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='nat_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(blank=True, null=True, related_name='doctor', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurse',
            field=models.ManyToManyField(blank=True, null=True, related_name='nurse', to='api.nurse'),
        ),
    ]
