# Generated by Django 4.1.5 on 2023-01-15 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='nurse',
            field=models.ManyToManyField(related_name='doctor_nurse', to='api.nurse'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='added_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='added_admin', to='api.admin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ManyToManyField(related_name='doctor', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nurse',
            field=models.ManyToManyField(related_name='nurse', to='api.nurse'),
        ),
    ]
