# Generated by Django 4.1.5 on 2023-01-26 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_patient_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'Users', 'verbose_name_plural': 'Users'},
        ),
    ]
