# Generated by Django 4.1.5 on 2023-01-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_user_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Specialization',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
