# Generated by Django 4.1.5 on 2023-02-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_user_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nat_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
