# Generated by Django 4.1.5 on 2023-01-26 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_options'),
        ('report', '0003_nursereport_doctorreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorreport',
            options={'ordering': ['-created'], 'verbose_name': 'Doctor Report', 'verbose_name_plural': 'Doctor Report'},
        ),
        migrations.AlterModelOptions(
            name='nursereport',
            options={'ordering': ['-created'], 'verbose_name': 'Nurse Report', 'verbose_name_plural': 'Nurse Report'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['created'], 'verbose_name': 'Report', 'verbose_name_plural': 'Report'},
        ),
        migrations.RemoveField(
            model_name='doctorreport',
            name='nurse',
        ),
        migrations.AddField(
            model_name='doctorreport',
            name='nurse',
            field=models.ManyToManyField(related_name='nurse_reports', to='api.nurse'),
        ),
    ]
