# Generated by Django 4.1.5 on 2023-01-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_user_options'),
        ('report', '0004_alter_doctorreport_options_alter_nursereport_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursereport',
            name='doctor',
        ),
        migrations.AddField(
            model_name='nursereport',
            name='doctor',
            field=models.ManyToManyField(related_name='doctors_reports', to='api.doctor'),
        ),
    ]
