# Generated by Django 4.1.5 on 2023-01-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminRegister',
        ),
    ]
