# Generated by Django 4.1.5 on 2023-01-29 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admins', '0002_rename_admin_adminregister'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminregister',
            options={'ordering': ['active']},
        ),
    ]
