# Generated by Django 4.1.5 on 2023-01-18 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0017_alter_doctor_nurse_alter_patient_added_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'Medicines',
                'verbose_name_plural': 'Medicines',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=1)),
                ('dosage', models.CharField(max_length=100)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_medicine', to=settings.AUTH_USER_MODEL)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_name', to='medicine.medicines')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='nurse_medicine', to='api.nurse')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_medicine', to='api.patient')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicine',
            },
        ),
    ]
