# Generated by Django 4.1.5 on 2023-01-18 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medicine', '0002_remove_medicine_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_medicine', to=settings.AUTH_USER_MODEL),
        ),
    ]
