# Generated by Django 4.1.5 on 2023-01-20 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_patient_address'),
        ('medicine', '0003_medicine_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_medicine', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='nurse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_medicine', to='api.nurse'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_medicine', to='api.patient'),
        ),
    ]
