# Generated by Django 4.1.5 on 2023-01-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_alter_medicine_doctor_alter_medicine_nurse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='medicines',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medicines',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
