# Generated by Django 4.1.5 on 2023-01-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_patient_phone'),
        ('medicine', '0005_medicine_created_medicine_updated_medicines_created_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['-updated'], 'verbose_name': 'Medicine', 'verbose_name_plural': 'Medicine'},
        ),
        migrations.AlterModelOptions(
            name='medicines',
            options={'ordering': ['-updated'], 'verbose_name': 'Medicines', 'verbose_name_plural': 'Medicines'},
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='nurse',
        ),
        migrations.AddField(
            model_name='medicine',
            name='nurse',
            field=models.ManyToManyField(related_name='nurse_medicine', to='api.nurse'),
        ),
    ]
